alter table HISTOGRAMA drop constraint FK9096177DBEBD4F09
alter table PACIENTE drop constraint FK5B4D0371A5C4D6
alter table TURNO drop constraint FK4C79772BEBD4F09
drop table DOCTOR if exists
drop table HISTOGRAMA if exists
drop table PACIENTE if exists
drop table TURNO if exists
drop table USUARIO if exists
create table DOCTOR (id bigint generated by default as identity (start with 1), apellido varchar(255), direccion varchar(255), dni integer not null, edad integer not null, matricula integer not null, nombre varchar(255), telefono integer not null, primary key (id))
create table HISTOGRAMA (id bigint generated by default as identity (start with 1), cara varchar(255), dientes integer not null, tratamiento varchar(255), PACIENTE_ID bigint, primary key (id))
create table PACIENTE (id bigint generated by default as identity (start with 1), apellido varchar(255), direccion varchar(255), dni integer not null, edad integer not null, nombre varchar(255), obraSocial varchar(255), telefono integer not null, usuario_id bigint, primary key (id))
create table TURNO (codigo bigint generated by default as identity (start with 1), asistido bit not null, fecha timestamp, paciente_id bigint, primary key (codigo))
create table USUARIO (id bigint generated by default as identity (start with 1), password bigint not null, username varchar(255), primary key (id))
alter table HISTOGRAMA add constraint FK9096177DBEBD4F09 foreign key (PACIENTE_ID) references PACIENTE
alter table PACIENTE add constraint FK5B4D0371A5C4D6 foreign key (usuario_id) references USUARIO
alter table TURNO add constraint FK4C79772BEBD4F09 foreign key (paciente_id) references PACIENTE
